-- MySQL Script generated by MySQL Workbench
-- Thu Aug 19 20:16:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema park_trails
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema park_trails
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `park_trails` ;
USE `park_trails` ;

-- -----------------------------------------------------
-- Table `park_trails`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `park_trails`.`states` ;

CREATE TABLE IF NOT EXISTS `park_trails`.`states` (
  `state_id` INT UNSIGNED NOT NULL,
  `state_name` VARCHAR(45) NULL,
  `state_code` VARCHAR(45) NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `park_trails`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `park_trails`.`locations` ;

CREATE TABLE IF NOT EXISTS `park_trails`.`locations` (
  `location_id` INT UNSIGNED NOT NULL,
  `location_name` VARCHAR(100) NULL,
  `location_address` VARCHAR(45) NULL,
  `location_city` VARCHAR(45) NULL,
  `location_phone` VARCHAR(9) NULL,
  `states_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`location_id`, `states_id`),
  INDEX `fk_locations_states1_idx` (`states_id` ASC) VISIBLE,
  CONSTRAINT `fk_locations_states1`
    FOREIGN KEY (`states_id`)
    REFERENCES `park_trails`.`states` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `park_trails`.`trails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `park_trails`.`trails` ;

CREATE TABLE IF NOT EXISTS `park_trails`.`trails` (
  `trail_id` INT UNSIGNED NOT NULL,
  `trail_name` VARCHAR(100) NULL,
  `trail_distance` VARCHAR(50) NULL,
  `trail_rating` VARCHAR(45) NULL,
  `trail_type` VARCHAR(45) NULL,
  `trail_difficulty` VARCHAR(45) NULL,
  `location_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trail_id`, `location_id`),
  INDEX `fk_trails_locations1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_trails_locations1`
    FOREIGN KEY (`location_id`)
    REFERENCES `park_trails`.`locations` (`states_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `park_trails`.`amenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `park_trails`.`amenities` ;

CREATE TABLE IF NOT EXISTS `park_trails`.`amenities` (
  `amenity_id` INT UNSIGNED NOT NULL,
  `amenity_type` VARCHAR(45) NULL,
  `amenity_description` VARCHAR(250) NULL,
  PRIMARY KEY (`amenity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `park_trails`.`entrances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `park_trails`.`entrances` ;

CREATE TABLE IF NOT EXISTS `park_trails`.`entrances` (
  `entrance_id` INT UNSIGNED NOT NULL,
  `entrance_description` VARCHAR(200) ,
  `exit_description` VARCHAR(200) NULL,
  `parking_address` VARCHAR(100) NULL,
  `trail_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`entrance_id`, `trail_id`),
  INDEX `fk_entrances_trails1_idx` (`trail_id` ASC) VISIBLE,
  CONSTRAINT `fk_entrances_trails1`
    FOREIGN KEY (`trail_id`)
    REFERENCES `park_trails`.`trails` (`trail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `park_trails`.`visitors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `park_trails`.`visitors` ;

CREATE TABLE IF NOT EXISTS `park_trails`.`visitors` (
  `vistor_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(9) NULL,
  `email_address` VARCHAR(45) NULL,
  `locations_id` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`vistor_id`, `locations_id`),
  INDEX `fk_visitors_locations1_idx` (`locations_id` ASC) VISIBLE,
  CONSTRAINT `fk_visitors_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `park_trails`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `park_trails`.`parking_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `park_trails`.`parking_records` ;

CREATE TABLE IF NOT EXISTS `park_trails`.`parking_records` (
  `parking_record_id` INT UNSIGNED NOT NULL,
  `vehicle_description` VARCHAR(45) NULL,
  `entrance_time` DATETIME NULL,
  `exit_time` DATETIME NULL,
  `visitor_id` INT UNSIGNED NOT NULL,
  `entrance_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`parking_record_id`, `visitor_id`, `entrance_id`),
  INDEX `fk_parking_records_visitors1_idx` (`visitor_id` ASC) VISIBLE,
  INDEX `fk_parking_records_entrances1_idx` (`entrance_id` ASC) VISIBLE,
  CONSTRAINT `fk_parking_records_visitors`
    FOREIGN KEY (`visitor_id`)
    REFERENCES `park_trails`.`visitors` (`vistor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parking_records_entrances1`
    FOREIGN KEY (`entrance_id`)
    REFERENCES `park_trails`.`entrances` (`entrance_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `park_trails`.`trails_amenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `park_trails`.`trails_amenities` ;

CREATE TABLE IF NOT EXISTS `park_trails`.`trails_amenities` (
  `trail_id` INT UNSIGNED NOT NULL,
  `amenity_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trail_id`, `amenity_id`),
  INDEX `fk_trails_amenities_ameities1_idx` (`amenity_id` ASC) VISIBLE,
  CONSTRAINT `fk_trails_amenities_trails1`
    FOREIGN KEY (`trail_id`)
    REFERENCES `park_trails`.`trails` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trails_amenities_ameities1`
    FOREIGN KEY (`amenity_id`)
    REFERENCES `park_trails`.`amenities` (`amenity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
